# Generated by Django 6.0.3 on 2026-04-13 16:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_alter_subcontractor_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseplan',
            name='inbound_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='已入库数量'),
        ),
        migrations.AddField(
            model_name='purchaseplan',
            name='plan_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='计划数量'),
        ),
    ]
