# Generated by Django 6.0.3 on 2026-05-12 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_purchaseplan_inbound_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('management', '管理层'), ('material_dept', '物资部'), ('supplier', '供应商'), ('clerk', '材料员'), ('subcontractor', '分包商')], default='management', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', '筹备中'), ('active', '进行中'), ('completed', '已完工'), ('paused', '暂停')], db_index=True, default='active', max_length=20, verbose_name='项目状态'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['project', 'subcontractor'], name='inventory_c_project_dab23d_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['supplier', 'status'], name='inventory_d_supplie_2d1cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='materialplan',
            index=models.Index(fields=['project', 'plan_date'], name='inventory_m_project_236403_idx'),
        ),
        migrations.AddIndex(
            model_name='materialplanitem',
            index=models.Index(fields=['material'], name='inventory_m_materia_fbe673_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['contract', 'project'], name='inventory_m_contrac_891c84_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['period_end'], name='inventory_m_period__256826_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['operator'], name='inventory_o_operato_233614_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['contract', 'project'], name='inventory_s_contrac_054717_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['period_end'], name='inventory_s_period__e807c2_idx'),
        ),
    ]
