# Generated by Django 6.0.3 on 2026-05-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundrecord',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='存放位置'),
        ),
    ]
