# Generated by Django 6.0.3 on 2026-05-12 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_add_location_to_inbound_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontractlist',
            name='category',
        ),
        migrations.AddField(
            model_name='subcontractlist',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='subcontract_lists',
                to='inventory.subcontractcategory',
                verbose_name='分类',
                null=True,  # 旧数据无分类，允许为空
            ),
        ),
    ]
