# Generated by Django 6.0.3 on 2026-05-13 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_change_subcontract_list_category_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractlist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_lists', to='inventory.subcontractcategory', verbose_name='分类'),
        ),
    ]
