# Generated by Django 6.0.3 on 2026-05-13 17:16

from django.db import migrations


def convert_roles(apps, schema_editor):
    Profile = apps.get_model('inventory', 'Profile')
    Profile.objects.filter(role__in=['material_dept', 'clerk']).update(role='management')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_alter_subcontractlist_category'),
    ]

    operations = [
        migrations.RunPython(convert_roles),
    ]
